extensions: {}
cabal-file: project.cabal
version: 1
module-template: ! 'module MODULE_NAME where

'
modules:
  Main(src/Main.hs):
    target-type: console
    filename: src/Main.hs
  Eval:
    target-type: console
    filename: src/Eval.hs
  Ast:
    target-type: console
    filename: src/Ast.hs
  Parser:
    target-type: console
    filename: src/Parser.hs
